# Generated by Django 4.2.1 on 2023-05-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='role',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
